environment:
  matrix:
  - julia_version: 0.6
  - julia_version: 0.7
  - julia_version: 1.0
  - julia_version: latest

platform:
  - x86 # 32-bit
  - x64 # 64-bit

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia --depwarn=error -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia --depwarn=error -e "%JL_TEST_SCRIPT%"

# # Since we don't have any Windows specific code in this repo we'll avoid installing
# # Coverage which slows the serial Appveyor jobs.
# on_success:
#   - echo "%JL_CODECOV_SCRIPT%"
#   - C:\julia\bin\julia -e "%JL_CODECOV_SCRIPT%"
