environment:
  matrix:
  - julia_version: 0.6
  - julia_version: 0.7
  - julia_version: 1.0
  - julia_version: latest

platform:
  - x86 # 32-bit
  - x64 # 64-bit

install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/omus/Appveyor.jl/cv/coverage-upload/bin/install.ps1"))

build_script:
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"

test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"

on_success:
  - echo "%JL_SUCCESS_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_SUCCESS_SCRIPT%"
