name: Format
on:
  pull_request:
    paths:
      - "**.jl"
      - ".github/workflows/Format.yml"
jobs:
  format:
    # These permissions are needed to:
    # - Checkout the repo
    # - Delete old caches: https://github.com/julia-actions/cache#usage
    # - Post formatting suggestions: https://github.com/reviewdog/action-suggester#required-permissions
    permissions:
      actions: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: "1"
      - uses: julia-actions/cache@v2
      - name: Install JuliaFormatter
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.add(PackageSpec(name="JuliaFormatter", version="1"))
      - name: Check Formatting
        shell: julia --color=yes {0}
        run: |
          using JuliaFormatter
          format("."; verbose=true)
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: JuliaFormatter
          fail_on_error: true
